version: '3'

services:
  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - '4200:4200'

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
